version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
permissions:
  - object: /home/ubuntu/app/scripts/
    pattern: "**"
    mode: 755
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: ubuntu