version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
permissions:
  - object: /home/ec2-user/app/scripts/
    pattern: "**"
    mode: 755
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 80
      runas: ec2-user