version: 0.2

phases:
  build:
    commands:
      - ./gradlew clean
      - echo Build started on `date`
      - ./gradlew build -x test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Listen files in the directory:"
      - ls -lR

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**/*